# QCTO - Workplace Module

### Project Title: Detection of Fraudulent Insurance Claims
#### Done By: Moosa Molibeli

© ExploreAI 2024

---

## Table of Contents

<a href=#BC> Background Context</a>

<a href=#one>1. Importing Packages</a>

<a href=#two>2. Data Collection and Description</a>

<a href=#three>3. Loading Data </a>

<a href=#four>4. Data Cleaning and Filtering</a>

<a href=#five>5. Exploratory Data Analysis (EDA)</a>

<a href=#six>6. Modeling </a>

<a href=#seven>7. Evaluation and Validation</a>

<a href=#eight>8. Final Model</a>

<a href=#nine>9. Conclusion and Future Work</a>

<a href=#ten>10. References</a>

---
 <a id="BC"></a>
## **Background Context**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Introduce the project, outline its goals, and explain its significance.
* **Details:** Include information about the problem domain, the specific questions or challenges the project aims to address, and any relevant background information that sets the stage for the work.
---

With the growing population of cars and the auto indsustry, car insurance ahas become an essential sector linked not only to economic growth, but also to people's lives. However, with the rapidly evolving landscape of digital finance and the expansion of online insurance services, the insurance industry faces an increasing threat from fraudulent activities that continues to increase in sophistication. The traditional rule-based systems that have always been used in traditional insurance, are now showing significant weaknesses against the dynamic strategies of modern digital fraudsters. Insurance fraud not only lowers earnings in the insurance business, leading to substantial losses but also impacts the price strategy of the insurance firm in the long run. According to Aslam et al., insurance fraud in America is expected to cost more than $40 billion each year in total. Therefore, it is critical to investigate the relationship between fraud detection and car insurance.

This project aims to investigate how manchine learning can be used to enhance the detection and prediction of fraudulent insurance claims.

The main goals of this project are therefore to: 
* Use machine learning algorithms to analyze large volumes of claim data to identify patterns and anomalies and provide actionable insights for decision-makers
* Develop a replicable model for detecting & predicting the likelihood of a claim being fraudulent
* Demonstrating how adopting advanced machine learning fraud detection methods can lead to increased resource optimization & cost saving for insurance companies.

The ultimate goal is to modernize and strengthen existing insurance frameworks and promote a shift towards data-driven decision-making where technology supports and enhances human interventions. 

Insurance fraud detection is important in helping to prevent significant financial losses, maintaining customer confidence and protecting the insurer's reputation, as well as ensuring adherence to industry regulations. So once an advanced fraud detection system has been put in place, insurers will be able to streamline the claims process and optimise resource allocation. It will also enable the insurer to understand the vulnerabilities in their processes and strengthen defenses against future attempts.

Fraud detection is an important aspect of modern financial institutions, especially in technical areas that are important and sensitive. The frequency of financial frauds has increased noticeably, particularly iin the car insurance industry, further reinforcing the signidficance of predictive modelling of fraudulent insurance claims.

---
<a href=#one></a>
## **Importing Packages**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Set up the Python environment with necessary libraries and tools.
* **Details:** List and import all the Python packages that will be used throughout the project such as Pandas for data manipulation, Matplotlib/Seaborn for visualization, scikit-learn for modeling, etc.
---

In [2]:
# importing the packages needed for this project

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold, cross_val_score
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.feature_selection import mutual_info_regression
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_squared_log_error
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.ensemble import VotingRegressor
from sklearn.ensemble import StackingRegressor

import warnings
warnings.filterwarnings('ignore')

# these are the top of mind libraries. But as more is required, more will be added

---
<a href=#two></a>
## **Data Collection and Description**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Describe how the data was collected and provide an overview of its characteristics.
* **Details:** Mention sources of the data, the methods used for collection (e.g., APIs, web scraping, datasets from repositories), and a general description of the dataset including size, scope, and types of data available (e.g., numerical, categorical).
---

The dataset used for this project is the 'Insurance_claims_raw.xlsx' dataset. It includes various variables related to insurance claims, such as customer duration, age, policy details, and incident specifics. The dataset was sourced from the Explore AI GitHub repoisitory, which was forked onto my own GitHub account in order to gain full access to it. 

The dataset comprises numerical and categorical data, including policy numbers, claim amounts, incident types, and demographic details like age and educational level. It is structured in such a way as to cover the entire scope of insurance claims, from policy initiation to incident reporting, enabling detailed analysis of fraudulent activities. From observation, the dataset's comprehensive nature supports robust fraud detection modeling. 

From quick observation of the dataset, it comprises 1000 observations and 40 variables.

Below is an explanation of each variable in the dataset:

In [3]:
import pandas as pd

# Data for the table
data = {
    "Column Name": [
        "age", "policy_number", "policy_bind_date", "policy_state", "policy_csl",
        "policy_deductable", "policy_annual_premium", "umbrella_limit", "insured_zip",
        "insured_sex", "insured_education_level", "insured_occupation", "insured_hobbies",
        "insured_relationship", "capital-gains", "capital-loss", "incident_date",
        "incident_type", "collision_type", "incident_severity", "authorities_contacted",
        "incident_state", "incident_city", "incident_location", "incident_hour_of_the_day",
        "number_of_vehicles_involved", "property_damage", "bodily_injuries", "witnesses",
        "police_report_available", "total_claim_amount", "injury_claim", "property_claim",
        "vehicle_claim", "auto_make", "auto_model", "auto_year", "fraud_reported"
    ],
    "Description": [
        "Age of the insured person.", "Unique number assigned to the insurance policy.",
        "Date when the policy was initiated.", "State where the policy was issued.",
        "Combined Single Limit – Coverage limit per accident.", "Amount the insured pays out of pocket before the insurer pays the claim.",
        "Yearly premium amount for the insurance policy.", "Additional liability coverage limit beyond the standard policy.",
        "ZIP code of the insured individual.", "Gender of the insured individual.", 
        "Education level of the insured (e.g., MD, PhD, Associate).", "Occupation of the insured person.",
        "Hobbies of the insured individual.", "Relationship status of the insured (e.g., husband, unmarried).",
        "Profit from the sale of assets like stocks or property.", "Loss from the sale of assets.",
        "Date when the incident occurred.", "Type of incident (e.g., Vehicle Theft, Single Vehicle Collision).",
        "Specific type of collision (e.g., Rear Collision, Front Collision).", 
        "Severity of the incident (e.g., Minor Damage, Major Damage).", 
        "Authorities that were contacted post-incident (e.g., Police).", "State where the incident took place.",
        "City where the incident occurred.", "Exact location/address of the incident.", 
        "Hour of the day when the incident occurred.", "Total number of vehicles involved in the incident.",
        "Whether there was property damage (YES, NO, or ? if uncertain).", "Number of bodily injuries sustained during the incident.",
        "Number of witnesses present at the time of the incident.", "Indicates whether a police report was available (YES, NO, or ? if uncertain).",
        "Total claim amount for the incident.", "Claim amount for injuries.", "Claim amount for property damages.",
        "Claim amount for vehicle damages.", "Make/brand of the vehicle involved.", "Model of the vehicle involved.",
        "Year of manufacture of the vehicle.", "Indicates whether the claim was fraudulent (Y for Yes, N for No)."
    ]
}

# Create a DataFrame
Data_Description = pd.DataFrame(data)

# Display the DataFrame
Data_Description

,Column Name,Description
0,age,Age of the insured person.
1,policy_number,Unique number assigned to the insurance policy.
2,policy_bind_date,Date when the policy was initiated.
3,policy_state,State where the policy was issued.
4,policy_csl,Combined Single Limit – Coverage limit per acc...
5,policy_deductable,Amount the insured pays out of pocket before t...
6,policy_annual_premium,Yearly premium amount for the insurance policy.
7,umbrella_limit,Additional liability coverage limit beyond the...
8,insured_zip,ZIP code of the insured individual.
9,insured_sex,Gender of the insured individual.
10,insured_education_level,"Education level of the insured (e.g., MD, PhD,..."
11,insured_occupation,Occupation of the insured person.
12,insured_hobbies,Hobbies of the insured individual.
13,insured_relationship,"Relationship status of the insured (e.g., husb..."
14,capital-gains,Profit from the sale of assets like stocks or ...
15,capital-loss,Loss from the sale of assets.
16,incident_date,Date when the incident occurred.
17,incident_type,"Type of incident (e.g., Vehicle Theft, Single ..."
18,collision_type,"Specific type of collision (e.g., Rear Collisi..."
19,incident_severity,"Severity of the incident (e.g., Minor Damage, ..."
20,authorities_contacted,Authorities that were contacted post-incident ...
21,incident_state,State where the incident took place.
22,incident_city,City where the incident occurred.
23,incident_location,Exact location/address of the incident.
24,incident_hour_of_the_day,Hour of the day when the incident occurred.
25,number_of_vehicles_involved,Total number of vehicles involved in the incid...
26,property_damage,"Whether there was property damage (YES, NO, or..."
27,bodily_injuries,Number of bodily injuries sustained during the...
28,witnesses,Number of witnesses present at the time of the...
29,police_report_available,Indicates whether a police report was availabl...
30,total_claim_amount,Total claim amount for the incident.
31,injury_claim,Claim amount for injuries.
32,property_claim,Claim amount for property damages.
33,vehicle_claim,Claim amount for vehicle damages.
34,auto_make,Make/brand of the vehicle involved.
35,auto_model,Model of the vehicle involved.
36,auto_year,Year of manufacture of the vehicle.
37,fraud_reported,Indicates whether the claim was fraudulent (Y ...

---
<a href=#three></a>
## **Loading Data**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Load the data into the notebook for manipulation and analysis.
* **Details:** Show the code used to load the data and display the first few rows to give a sense of what the raw data looks like.
---

In [4]:
# loading the dataset 
df = pd.read_excel('insurance_claims_raw.xlsx')
df.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
0,328,48.0,521585,2014-10-17,OH,250/500,1000.0,1406.91,0,466132,...,YES,71610.0,6510.0,13020.0,52080,Saab,92x,2004,Y,NaN
1,228,42.0,342868,2006-06-27,IN,250/500,2000.0,1197.22,5000000,468176,...,?,5070.0,780.0,780.0,3510,Mercedes,E400,2007,Y,NaN
2,134,29.0,687698,2000-09-06,OH,100/300,2000.0,1413.14,5000000,430632,...,NO,34650.0,7700.0,3850.0,23100,Dodge,RAM,2007,N,NaN
3,256,41.0,227811,1990-05-25,IL,250/500,2000.0,1415.74,6000000,608117,...,NO,63400.0,6340.0,6340.0,50720,Chevrolet,Tahoe,2014,Y,NaN
4,228,44.0,367455,2014-06-06,IL,500/1000,1000.0,1583.91,6000000,610706,...,NO,6500.0,1300.0,650.0,4550,Accura,RSX,2009,N,NaN

---
<a href=#four></a>
## **Data Cleaning and Filtering**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Prepare the data for analysis by cleaning and filtering.
* **Details:** Include steps for handling missing values, removing outliers, correcting errors, and possibly reducing the data (filtering based on certain criteria or features).
---

Introduction

Data cleaning and preprocessing are essential steps in preparing a dataset for analysis. These processes involve handling missing values, duplicates &  outliers In this stage, I will endeavour to perserve the quality and integrity of our dataset while preparing it for unbiased insights that will not mislead stakeholders

#### Step 1:
##### Understanding the data structure

We will begin firstly by understanding the data structure by displaying things such as the shape of the dataframe to understand how many observations and predictors I have in the dataset (where predictors = columns-1), and the data types to ensure they are appropriate, but also to understand the type of manipulation that will be required during feature selection and prediction stages. Lastly, wI will also take a look at the basic statistics. This should give us a little more information around spread & any obvious outliers in the data. 

But first, I will start by creating a copy of our dataframe that I will use for the remainder of the project. This is to ensure if anything is accidently lost in the clean-up stage, we can revert back to the original dataset.

In [5]:
# creating a copy of the dataset
df_copy = df.copy()

In [6]:
# getting the shape of the dataset
df_copy.shape

(1000, 40)

Observation:

There are 1000 observations in our dataset and 39 predictor variables that we will be working with. Feature selection might be a necessary step here so as to avoid overfitting as there are quite a few predictor variables.

In [7]:
# displaying the first few rows of the dataset to get a sense of the columns in the dataset
df_copy.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
0,328,48.0,521585,2014-10-17,OH,250/500,1000.0,1406.91,0,466132,...,YES,71610.0,6510.0,13020.0,52080,Saab,92x,2004,Y,NaN
1,228,42.0,342868,2006-06-27,IN,250/500,2000.0,1197.22,5000000,468176,...,?,5070.0,780.0,780.0,3510,Mercedes,E400,2007,Y,NaN
2,134,29.0,687698,2000-09-06,OH,100/300,2000.0,1413.14,5000000,430632,...,NO,34650.0,7700.0,3850.0,23100,Dodge,RAM,2007,N,NaN
3,256,41.0,227811,1990-05-25,IL,250/500,2000.0,1415.74,6000000,608117,...,NO,63400.0,6340.0,6340.0,50720,Chevrolet,Tahoe,2014,Y,NaN
4,228,44.0,367455,2014-06-06,IL,500/1000,1000.0,1583.91,6000000,610706,...,NO,6500.0,1300.0,650.0,4550,Accura,RSX,2009,N,NaN

In [8]:
# getting a summary of the dataframe in terms of data types
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           1000 non-null   int64
 1   age                          998 non-null    float64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   datetime64[ns]
 4   policy_state                 1000 non-null   object
 5   policy_csl                   1000 non-null   object
 6   policy_deductable            998 non-null    float64
 7   policy_annual_premium        997 non-null    float64
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   object
 11  insured_education_level      999 non-null    object
 12  insured_occupation           1000 non-null   object
 13  insured_hobbies              998 non-null    object
 14  insured_relationship         1000 non-null   object
 15  capital-gains                998 non-null    float64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   datetime64[ns]
 18  incident_type                1000 non-null   object
 19  collision_type               1000 non-null   object
 20  incident_severity            1000 non-null   object
 21  authorities_contacted        907 non-null    object
 22  incident_state               998 non-null    object
 23  incident_city                1000 non-null   object
 24  incident_location            1000 non-null   object
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   object
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   object
 31  total_claim_amount           996 non-null    float64
 32  injury_claim                 999 non-null    float64
 33  property_claim               999 non-null    float64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   object
 36  auto_model                   1000 non-null   object
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   object
 39  _c39                         0 non-null      float64
dtypes: datetime64[ns](2), float64(8), int64(11), object(19)
memory usage: 312.6+ KB

Observation: 

* The dataset seems largely complete, with only a few columns exhibiting missing data. Handling the missing values appropriately is crucial for accurate analysis.

* The dataset includes a mix of numerical, categorical, and datetime columns, which allows for diverse types of analysis.
Categorical columns might need encoding for machine learning tasks.

* There could be potential redundancies. The column _c39 has no data and should be removed to clean up the dataset.

In [9]:
# getting the basic statistics of the variables in the dataset
print(df_copy.describe())

       months_as_customer         age  policy_number  \
count         1000.000000  998.000000    1000.000000
mean           203.954000   38.962926  546238.648000
min              0.000000   19.000000  100804.000000
25%            115.750000   32.000000  335980.250000
50%            199.500000   38.000000  533135.000000
75%            276.250000   44.000000  759099.750000
max            479.000000   64.000000  999435.000000
std            115.113174    9.135425  257063.005276

                    policy_bind_date  policy_deductable  \
count                           1000         998.000000
mean   2002-02-08 04:40:47.999999872        1134.268537
min              1990-01-08 00:00:00         500.000000
25%              1995-09-19 00:00:00         500.000000
50%              2002-04-01 12:00:00        1000.000000
75%              2008-04-21 12:00:00        2000.000000
max              2015-02-22 00:00:00        2000.000000
std                              NaN         611.251914

       policy_annual_premium  umbrella_limit    insured_zip  capital-gains  \
count             997.000000    1.000000e+03    1000.000000     998.000000
mean             1257.001113    1.101000e+06  501214.488000   25176.452906
min               433.330000   -1.000000e+06  430104.000000       0.000000
25%              1090.320000    0.000000e+00  448404.500000       0.000000
50%              1257.830000    0.000000e+00  466445.500000       0.000000
75%              1415.740000    0.000000e+00  603251.000000   51075.000000
max              2047.590000    1.000000e+07  620962.000000  100500.000000
std               244.265051    2.297407e+06   71701.610941   27877.379027

        capital-loss  ... incident_hour_of_the_day  \
count    1000.000000  ...              1000.000000
mean   -26793.700000  ...                11.644000
min   -111100.000000  ...                 0.000000
25%    -51500.000000  ...                 6.000000
50%    -23250.000000  ...                12.000000
75%         0.000000  ...                17.000000
max         0.000000  ...                23.000000
std     28104.096686  ...                 6.951373

       number_of_vehicles_involved  bodily_injuries    witnesses  \
count                   1000.00000      1000.000000  1000.000000
mean                       1.83900         0.992000     1.487000
min                        1.00000         0.000000     0.000000
25%                        1.00000         0.000000     1.000000
50%                        1.00000         1.000000     1.000000
75%                        3.00000         2.000000     2.000000
max                        4.00000         2.000000     3.000000
std                        1.01888         0.820127     1.111335

       total_claim_amount  injury_claim  property_claim  vehicle_claim  \
count          996.000000    999.000000      999.000000    1000.000000
mean         52767.469880   7434.944945     7398.628629   37928.950000
min            100.000000      0.000000        0.000000      70.000000
25%          41812.500000   4290.000000     4440.000000   30292.500000
50%          57935.000000   6780.000000     6750.000000   42100.000000
75%          70620.000000  11310.000000    10890.000000   50822.500000
max         114920.000000  21450.000000    23670.000000   79560.000000
std          26405.348039   4883.158265     4827.050887   18886.252893

         auto_year  _c39
count  1000.000000   0.0
mean   2005.103000   NaN
min    1995.000000   NaN
25%    2000.000000   NaN
50%    2005.000000   NaN
75%    2010.000000   NaN
max    2015.000000   NaN
std       6.015861   NaN

[8 rows x 21 columns]

Observations:

'policy_deductable' and 'policy_annual_premium': The wide range and significant standard deviation suggest there are significant differences in the amounts, possibly indicating different policies or coverage levels.

'umbrella_limit': The min value being in the negatives is a bit alarming. As this is additional liability coverage limit beyond the standard policy, it is odd that the number would be in the negatives. This would need to be investigated.

'capital-gains' and 'capital-loss': Large discrepancies between mean and median suggest extreme values or outliers. These columns should be reviewed for data entry errors or inconsistencies.

'total_claim_amount', 'injury_claim', 'property_claim', and 'vehicle_claim': All these columns have high variability, which could be due to outliers or large claims. The high standard deviations and ranges suggest these columns are crucial for understanding claims distribution.

#### Step 2: 
##### Handling Missing Values

Missing values can introduce inaccuracies and create bias in the analysis. So, it is important identify them and handle them appropriately. To do this, I will get the sum of all isnull rows for each column in the dataframely

In [10]:
# checking for missing values
df_copy.isnull().sum()

months_as_customer                0
age                               2
policy_number                     0
policy_bind_date                  0
policy_state                      0
policy_csl                        0
policy_deductable                 2
policy_annual_premium             3
umbrella_limit                    0
insured_zip                       0
insured_sex                       0
insured_education_level           1
insured_occupation                0
insured_hobbies                   2
insured_relationship              0
capital-gains                     2
capital-loss                      0
incident_date                     0
incident_type                     0
collision_type                    0
incident_severity                 0
authorities_contacted            93
incident_state                    2
incident_city                     0
incident_location                 0
incident_hour_of_the_day          0
number_of_vehicles_involved       0
property_damage                   0
bodily_injuries                   0
witnesses                         0
police_report_available           0
total_claim_amount                4
injury_claim                      1
property_claim                    1
vehicle_claim                     0
auto_make                         0
auto_model                        0
auto_year                         0
fraud_reported                    0
_c39                           1000
dtype: int64

Observation:

There are 9 columns with missing/null values, majority of which have less than 4 missing values. I will be using the interpolation method to replace the missing values. Interpolation will estimate the missing values based on surrounding data points, which can perserve the data's natural trend patterns. By using nearby values, interpolation will also maintain some of the variability in the data, avoiding the reduction in the variability that can occur with the mean/median imputation. 

However, for the one variable - 'authorities_contracted' - which has 93 missing values, more investigation is required in order to make an informed decision as to how to handle this column.

In [25]:
# interpolation of the missing/null values in all the other columns, excluding 'authorities_contacted'
df_copy['age'] = df_copy['age'].interpolate(method='linear')
df_copy['policy_deductable'] = df_copy['policy_deductable'].interpolate(method='linear')
df_copy['policy_annual_premium'] = df_copy['policy_annual_premium'].interpolate(method='linear')
df_copy['insured_education_level'] = df_copy['insured_education_level'].interpolate(method='linear')
df_copy['insured_hobbies'] = df_copy['insured_hobbies'].interpolate(method='linear')
df_copy['capital-gains'] = df_copy['capital-gains'].interpolate(method='linear')
df_copy['incident_state'] = df_copy['incident_state'].interpolate(method='linear')
df_copy['total_claim_amount'] = df_copy['total_claim_amount'].interpolate(method='linear')
df_copy['injury_claim'] = df_copy['injury_claim'].interpolate(method='linear')
df_copy['property_claim'] = df_copy['property_claim'].interpolate(method='linear')

In [11]:
# verifying that the missing data has been filled
df_copy.isnull().sum()

months_as_customer                0
age                               2
policy_number                     0
policy_bind_date                  0
policy_state                      0
policy_csl                        0
policy_deductable                 2
policy_annual_premium             3
umbrella_limit                    0
insured_zip                       0
insured_sex                       0
insured_education_level           1
insured_occupation                0
insured_hobbies                   2
insured_relationship              0
capital-gains                     2
capital-loss                      0
incident_date                     0
incident_type                     0
collision_type                    0
incident_severity                 0
authorities_contacted            93
incident_state                    2
incident_city                     0
incident_location                 0
incident_hour_of_the_day          0
number_of_vehicles_involved       0
property_damage                   0
bodily_injuries                   0
witnesses                         0
police_report_available           0
total_claim_amount                4
injury_claim                      1
property_claim                    1
vehicle_claim                     0
auto_make                         0
auto_model                        0
auto_year                         0
fraud_reported                    0
_c39                           1000
dtype: int64

Observation:

We note that 'insured_education_level' , 'insured_hobbies' & 'incident_state' did not fill in missing values during the interpolation approach. This is because interpolation is best suited for numerical values and these variables seem to be categorical in nature. So, for these I will use the mode imputation which will replace the missing values with the most frequently occuring value in the column. This is a common approach for categorical data, and given that at most for one column I will only be replacing 2 missing values, I feel comfortable to do so.

In [27]:
# Replace missing values with the mode for categorical columns
df_copy['insured_education_level'].fillna(df_copy['insured_education_level'].mode()[0], inplace=True)
df_copy['insured_hobbies'].fillna(df_copy['insured_hobbies'].mode()[0], inplace=True)
df_copy['incident_state'].fillna(df_copy['incident_state'].mode()[0], inplace=True)

In [12]:
# verifying that the missing data has been filled
df_copy.isnull().sum()

months_as_customer                0
age                               2
policy_number                     0
policy_bind_date                  0
policy_state                      0
policy_csl                        0
policy_deductable                 2
policy_annual_premium             3
umbrella_limit                    0
insured_zip                       0
insured_sex                       0
insured_education_level           1
insured_occupation                0
insured_hobbies                   2
insured_relationship              0
capital-gains                     2
capital-loss                      0
incident_date                     0
incident_type                     0
collision_type                    0
incident_severity                 0
authorities_contacted            93
incident_state                    2
incident_city                     0
incident_location                 0
incident_hour_of_the_day          0
number_of_vehicles_involved       0
property_damage                   0
bodily_injuries                   0
witnesses                         0
police_report_available           0
total_claim_amount                4
injury_claim                      1
property_claim                    1
vehicle_claim                     0
auto_make                         0
auto_model                        0
auto_year                         0
fraud_reported                    0
_c39                           1000
dtype: int64

Observation:

I have successfully replaced the missing values for this dataset, with the exception of 'authorities_contracted'. Given that this column has 93 values missing, which is about 9.3% of the dataset, I don't feel comfortable imputing these values. It is therefore important to assess the importance of this variable on our investigation for detecting fraudulent claims. If the column is not at all important, I will feel most comfortable dropping the column all together.

The variable 'authorities_contacted' refers to authorities that were contacted post-incident (e.g., Police, Fire). At this stage of the project, the authorities contacted post the incident does not have much to do with whether the claim could be fraudulent or not. In fact, the claimant would need to report the incident to authorities in order to legitimise their claim. As a result, I will opt to drop the column completely.

In [13]:
# dropping the 'authorities_contacted' column from the dataframe
df_copy = df_copy.drop(columns=['authorities_contacted'])

In [14]:
# verifying that the column was dropped
print(df_copy.head(2))

   months_as_customer   age  policy_number policy_bind_date policy_state  \
0                 328  48.0         521585       2014-10-17           OH
1                 228  42.0         342868       2006-06-27           IN

  policy_csl  policy_deductable  policy_annual_premium  umbrella_limit  \
0    250/500             1000.0                1406.91               0
1    250/500             2000.0                1197.22         5000000

   insured_zip  ... police_report_available total_claim_amount injury_claim  \
0       466132  ...                     YES            71610.0       6510.0
1       468176  ...                       ?             5070.0        780.0

  property_claim vehicle_claim  auto_make  auto_model auto_year  \
0        13020.0         52080       Saab         92x      2004
1          780.0          3510   Mercedes        E400      2007

  fraud_reported _c39
0              Y  NaN
1              Y  NaN

[2 rows x 39 columns]

As mentioned earlier, column '_c39' has missing data and could potentially have redundencies. As a result, I have concluded to remove it from the dataset.

In [15]:
# dropping the 'authorities_contacted' column from the dataframe
df_copy = df_copy.drop(columns=['_c39'])

In [16]:
# verifying that the column was dropped
print(df_copy.head(2))

   months_as_customer   age  policy_number policy_bind_date policy_state  \
0                 328  48.0         521585       2014-10-17           OH
1                 228  42.0         342868       2006-06-27           IN

  policy_csl  policy_deductable  policy_annual_premium  umbrella_limit  \
0    250/500             1000.0                1406.91               0
1    250/500             2000.0                1197.22         5000000

   insured_zip  ... witnesses police_report_available total_claim_amount  \
0       466132  ...         2                     YES            71610.0
1       468176  ...         0                       ?             5070.0

  injury_claim property_claim  vehicle_claim  auto_make auto_model auto_year  \
0       6510.0        13020.0          52080       Saab        92x      2004
1        780.0          780.0           3510   Mercedes       E400      2007

  fraud_reported
0              Y
1              Y

[2 rows x 38 columns]

#### Step 3: 
##### Handling Duplicate Observations

Duplicates can skew statistical data, leading to inaccurate insights and conclusions. By identifying duplicates and removing them, I will perserve the integrity of our dataset

In [17]:
# checking for duplicate rows
df_copy.duplicated().sum()

0

Observation:

Our dataset does not have any duplicates as the output of our check returned 0. This means we can confidently move ahead with any statistical analysis knowing that our data is of good quality

#### Step 4:
##### Handling Outliers

Handling outliers is a critical step in ensuring that your data and models are robust, accurate, and reliable.

I will be using the IQR method to identify any outliers in the data. 

The IQR method is a robust statisitcal technique for identifying outliers by leveraging from the spread of the data. It is useful for identifying extreme values that deviate from the majority of the dataset, helping me clean the data for accurate analysis and modeling.

In [18]:
# Identify and handle outliers in all the numeric columns
numeric_cols = ['months_as_customer', 'age', 'policy_deductable', 'policy_annual_premium', 'umbrella_limit',
    'insured_zip', 'capital-gains', 'capital-loss', 'incident_hour_of_the_day', 'number_of_vehicles_involved',
    'bodily_injuries', 'witnesses', 'total_claim_amount', 'injury_claim', 'property_claim', 'vehicle_claim',
    'auto_year']

# Calculate quartiles and IQR for each numeric column
for col in numeric_cols:
    Q1 = df_copy[col].quantile(0.25)
    Q3 = df_copy[col].quantile(0.75)
    IQR = Q3 - Q1
    
    # Identify outliers
    outliers = (df_copy[col] < Q1 - 1.5 * IQR) | (df_copy[col] > Q3 + 1.5 * IQR)
    
    # Remove outliers
    df_copy = df_copy[~outliers]

df_copy.shape

(783, 38)

Observation:

This method has allowed me to remove outliers. In total, 21.8% of the dataset has been removed at this stage. I am confident in moving forward with only 782 observations as this is still over 70% of the dataset. Additionally, this ensure that my data is more aligned for robust analysis and accurate modeling.

#### Step 5:
##### Column Formatting

This is the process of standardising data formats. This is in an effort to enhance data quality by ensuring consistency and standardization, easy of data interpretation and data validation. I will be removing spaces and special characters that may exist in the column names, and also ensuring consistent use of underscores as word seperators, instead of using a dash.

In [19]:
# removing column special characters and spaces
df_copy.columns = df_copy.columns.str.strip().str.replace(' ', '_').str.replace('.', '').str.replace('-','_').str.lower()
print (df_copy.columns)

Index(['months_as_customer', 'age', 'policy_number', 'policy_bind_date',
       'policy_state', 'policy_csl', 'policy_deductable',
       'policy_annual_premium', 'umbrella_limit', 'insured_zip', 'insured_sex',
       'insured_education_level', 'insured_occupation', 'insured_hobbies',
       'insured_relationship', 'capital_gains', 'capital_loss',
       'incident_date', 'incident_type', 'collision_type', 'incident_severity',
       'incident_state', 'incident_city', 'incident_location',
       'incident_hour_of_the_day', 'number_of_vehicles_involved',
       'property_damage', 'bodily_injuries', 'witnesses',
       'police_report_available', 'total_claim_amount', 'injury_claim',
       'property_claim', 'vehicle_claim', 'auto_make', 'auto_model',
       'auto_year', 'fraud_reported'],
      dtype='object')

---
<a href=#five></a>
## **Exploratory Data Analysis (EDA)**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Explore and visualize the data to uncover patterns, trends, and relationships.
* **Details:** Use statistics and visualizations to explore the data. This may include histograms, box plots, scatter plots, and correlation matrices. Discuss any significant findings.
---

In [ ]:
#Please use code cells to code in and do not forget to comment your code.

---
<a href=#six></a>
## **Modeling**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Develop and train predictive or statistical models.
* **Details:** Describe the choice of models, feature selection and engineering processes, and show how the models are trained. Include code for setting up the models and explanations of the model parameters.
---

In [ ]:
#Please use code cells to code in and do not forget to comment your code.

---
<a href=#seven></a>
## **Evaluation and Validation**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Evaluate and validate the effectiveness and accuracy of the models.
* **Details:** Present metrics used to evaluate the models, such as accuracy, precision, recall, F1-score, etc. Discuss validation techniques employed, such as cross-validation or train/test split.
---

In [ ]:
#Please use code cells to code in and do not forget to comment your code.

---
<a href=#eight></a>
## **Final Model**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Present the final model and its performance.
* **Details:** Highlight the best-performing model and discuss its configuration, performance, and why it was chosen over others.
---

In [ ]:
#Please use code cells to code in and do not forget to comment your code.

---
<a href=#nine></a>
## **Conclusion and Future Work**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Summarize the findings and discuss future directions.
* **Details:** Conclude with a summary of the results, insights gained, limitations of the study, and suggestions for future projects or improvements in methodology or data collection.
---

In [ ]:
#Please use code cells to code in and do not forget to comment your code.

---
<a href=#ten></a>
## **References**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Provide citations and sources of external content.
* **Details:** List all the references and sources consulted during the project, including data sources, research papers, and documentation for tools and libraries used.
---

1. Aslam, F., Hunjra, A.I., Ftiti, Z., Louhichi, W. & Shams, T., 2024. Insurance fruad detection: Evidence from artificial intelligence and machine learning. Reasearch in International Business and Finance, Volume 62, December 2023, 101744. Available at: sciencedirect.com/article/abs/pii/S0275531922001325

2. Schrijiver, G., Sarmah, D.K. & El-hajj, M., 2024. Automobile insurance fraud detection using data mining: A systemic literature review. Intelligent Systems with Applications, Volume 21, March 2024, 200340. Available at: sciencedirect.com/science/article/pii/S2667305324000164

3. Al-Hashedi, K.G. & Magalingam, P. 2021. Financial fraud detection applying data mining technoques: A comprehensive review from 2009 to 2019. Computer Science Review, Volume 40, May 2021, 100402. Available at: sciencedirect.com/science/article/abs/pii/S1574013721000423

## Additional Sections to Consider

* ### Appendix: 
For any additional code, detailed tables, or extended data visualizations that are supplementary to the main content.

* ### Contributors: 
If this is a group project, list the contributors and their roles or contributions to the project.